app:
  scheduler:
    interval: 20s
  updater:
    interval: 2m
  database-access-type: jpa
  kafka:
    updates-topic:
      name: updates
      partitions: 1
      replicas: 1
  use-queue: true
  client:
    git:
      url: https://api.github.com
      codes: [500]
    stackoverflow:
      url: https://api.stackexchange.com/2.3
      codes: [404, 505]
      backoff-type: linear
    bot:
      url: http://localhost:8090
      backoff-type: constant
      duration: 3s

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  cache:
    cache-names:
    - scrapper-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
  - cache-name: scrapper-buckets
    url: /tg-chat/.*
    rate-limits:
    - cache-key: getRemoteAddr()
      bandwidths:
      - capacity: 20
        time: 1
        unit: minutes
  - cache-name: scrapper-buckets
    url: /links
    rate-limits:
    - cache-key: getRemoteAddr()
      bandwidths:
      - capacity: 20
        time: 1
        unit: minutes


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
